#!/usr/bin/env bash
set -ex

case "$1" in

 jitpack)
   exec $0 mill -j 0 __.publishM2Local
 ;;
 
 mill)
   exec $0 cs launch mill -- "${@:2}"
 ;;

 scalafmt)
   exec $0 cs launch scalafmt -- --mode diff --diff-branch master "${@:2}"
 ;;

 cs)
   test -x cs || {
     curl -o cs -qL https://git.io/coursier-cli
     chmod +x cs
   }
   exec ./cs "${@:2}"
 ;;

esac