#!/usr/bin/env bash
set -ex

BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

function die {
  echo "$*" >&2
  exit 1
}

case "$1" in

 jitpack)
   exec $0 mill -j 0 __.publishM2Local
 ;;

 mill)
   exec $0 cs launch "mill:$(< .mill-version)" -- "${@:2}"
 ;;

 scalafmt)
   exec $0 cs launch scalafmt -- --mode diff --diff-branch master "${@:2}"
 ;;

 cs)
   test -x $BASE_DIR/cs || {
     curl -o $BASE_DIR/cs -qL https://git.io/coursier-cli
     chmod +x $BASE_DIR/cs
   }
   exec $BASE_DIR/cs "${@:2}"
 ;;

 example)
   test -f example/secrets.env || die "Missing example/secrets.env"
   (
     cd example
     ../ci mill _.docker.build
     docker run --rm --env-file secrets.env -ti keybase-scala-example
   )
 ;;

 test)
   $0 mill -j 0 __.compile
   (cd example; ../ci mill example.compile)
   # $0 mill -j 0 __.tests
   $0 scalafmt --test
 ;;

 release)
   git tag $(<VERSION)
   git push --tags
 ;;

esac
